name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- UBAH INI ---
  camera: ^0.11.3   # Ganti dari 0.10.5 ke 0.11.3 agar cocok dengan flutter_vision 2.0.0

  # --- Tambahan ---
  flutter_vision: ^2.0.0
  permission_handler: ^11.3.0
  image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/alphabet/
    - assets/number/
    - assets/logo/
    # Ubah baris ini agar lebih spesifik:
    - assets/model/my_model.tflite
    - assets/model/labels.txt  # Jangan lupa labels jika ada